name: Continuous Integration

on:
  push:
    branches: [ main ]
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      # Terraform Initialization and Deployment
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.3

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Terraform Init
        working-directory: ./terraform-aks
        run: terraform init

      - name: Terraform Plan
        working-directory: ./terraform-aks
        run: terraform plan

      - name: Terraform Apply
        working-directory: ./terraform-aks
        run: terraform apply -auto-approve || true

      # Docker Build and Push
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build, tag, and push image to Docker Hub
        env:
          IMAGE_NAME: botros1/pwc-flaskapp
          IMAGE_TAG: latest
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG
